package com.rqpa.algo.tasks;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import com.rqpa.algo.numbers.GeometricNumbersGenerator;

/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
 */
public class Task45
{
    public static void main(String[] args)
    {
        System.out.println(findNextTriangleNumber());
    }
    public static long findNextTriangleNumber()
    {
        List<Long> triangleNumbers = new ArrayList<>();
        List<Long> pentagonalNumbers = new ArrayList<>();
        List<Long> hexagonalNumbers = new ArrayList<>();

        int nextIndexToCheck = 286;


        for (int i = 1; i < 100_000; i++)
        {
            triangleNumbers.add(GeometricNumbersGenerator.getTriangleNumber(i));
            pentagonalNumbers.add(GeometricNumbersGenerator.getPentagonalNumber(i));
            hexagonalNumbers.add(GeometricNumbersGenerator.getHexagonalNumber(i));
        }


        for (; nextIndexToCheck < hexagonalNumbers.size(); nextIndexToCheck++)
        {
            Long triangle = triangleNumbers.get(nextIndexToCheck);
            if (Collections.binarySearch(pentagonalNumbers, triangle) >= 0 && Collections.binarySearch(hexagonalNumbers, triangle) >= 0)
            {
                return triangle;
            }
        }

        throw new RuntimeException("Not found!");
    }
}
